package com.limachi.arss.client.keyboardSystem;

import com.limachi.arss.common.block_entities.KeyboardLectern;
import com.limachi.arss.common.items.Keyboard;
import net.fabricmc.api.EnvType;
import net.fabricmc.api.Environment;
import net.minecraft.client.Minecraft;
import net.minecraft.core.BlockPos;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.item.ItemStack;

import java.util.HashSet;
import java.util.Set;

@Environment(EnvType.CLIENT)
public class Origin {
    private final BlockPos lectern;
    private final int slot;

    public Origin(BlockPos lectern) {
        this.lectern = lectern;
        this.slot = -1;
    }

    public Origin(KeyboardLectern lectern) {
        this(lectern.getBlockPos());
    }

    public Origin(int slot) {
        this.slot = slot;
        this.lectern = null;
    }

    public ItemStack getKeyboard() {
        if (Minecraft.getInstance().player instanceof Player player) {
            if (lectern != null) {
                if (player.level().getBlockEntity(lectern) instanceof KeyboardLectern be)
                    return be.getKeyboard();
                return ItemStack.EMPTY;
            } else
                return player.getInventory().getItem(slot);
        }
        return ItemStack.EMPTY;
    }
/*
    //TODO: should be generated by the keyboard (lectern) itself on start using instead of queried
    public static Set<Origin> getOrigins() {
        Set<Origin> o = new HashSet<>();
        if (Minecraft.getInstance().player instanceof Player player) {
            var inventory = player.getInventory();
            for (int slot = 0; slot < inventory.getContainerSize(); slot++)
                if (inventory.getItem(slot).getItem() instanceof Keyboard)
                    o.add(new Origin(slot));
            for (KeyboardLectern lectern : KeyboardLectern.getControlled(player))
                if (lectern.getBlockPos().closerThan(player.blockPosition(), KeyboardHandler.LECTERN_REACH))
                    o.add(new Origin(lectern));
        }
        return o;
    }*/
}
