modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/LIMachi/arss/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://github.com/LIMachi/arss/blob/1.20.1/forge_changelog.json"
displayURL="https://legacy.curseforge.com/minecraft/mc-mods/analog-redstone-suite"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"


[[dependencies.${mod_id}]]
modId="lim_lib"
mandatory=true
versionRange="[${lim},)"
ordering="AFTER"
side="BOTH"