modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"
issueTrackerURL="https://github.com/LIMachi/arss/issues"

[[mods]]
    modId="arss"
    version="${file.jarVersion}"
    displayName="Analog Redstone Suite"
    updateJSONURL="https://raw.githubusercontent.com/LIMachi/arss/master/forge_changelog.json"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/analog-redstone-suite"
    #logoFile="arss.png"
    #credits=""
    authors="LIMachi"
    description=''' '''

[[dependencies.arss]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.arss]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.arss]]
    modId="lim_lib"
    mandatory=true
    versionRange="[1.19.2-A1.2.1,)"
    ordering="AFTER"
    side="BOTH"