modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "${license}"

[[mods]]
modId = "${archives_name}"
version = "${version}"
displayName = "${readable_name}"
authors = "${author}"
description = "${description}"
logoFile = "assets/${archives_name}/icon.png"

[[dependencies.${archives_name}]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${archives_name}]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${archives_name}]]
modId = "architectury"
type = "required"
versionRange = "[13.0.2,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${archives_name}]]
modId = "lim_lib"
type = "required"
versionRange = "[1.0.0,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "${archives_name}.mixins.json"

[[mixins]]
config = "${archives_name}-neo.mixins.json"