modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "${license}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${readable_name}"
authors = "${author}"
description = "${description}"
logoFile = "assets/${mod_id}/icon.png"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "architectury"
type = "required"
versionRange = "[13.0.2,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "lim_lib"
type = "required"
versionRange = "[${lim_lib_version},)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "${mod_id}.mixins.json"

[[mixins]]
config = "${mod_id}-neo.mixins.json"