modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "arss"
version = "${version}"
displayName = "Analog Redstone Suite"
authors = "Me!"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.arss]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.arss]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.arss]]
modId = "architectury"
type = "required"
versionRange = "[13.0.2,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "arss.mixins.json"
